
API_KEY = "ENTER_API_KEY"
NEWS_API_KEY ="ENTER_NEWS_API_KEY"
OPENAI_API_KEY ="sk_ENTER_OPENAI-API-KEY"
EMAIL_ADDRESS = "abc@gmail.com"
EMAIL_APP_PASSWORD = "sfghjiifgkjk"
DEFAULT_EMAIL_TO = "xyz@gmail.com"
